include:
  - .gitlab-ci/job-definitions.yml
  - .gitlab-ci/global-declarations.yml
  - .gitlab-ci/devices.yml

rootfs-amd64-graphical:
  extends:
    - .rootfs-generic
    - .arch-amd64
    - .environment-graphical

rootfs-arm64-graphical:
  extends:
    - .rootfs-generic
    - .arch-arm64
    - .environment-graphical

rootfs-arm64-graphical-staging:
  variables:
    MOBIAN_SUITE: "staging"
  extends:
    - .rootfs-generic
    - .arch-arm64
    - .environment-graphical

installfs-arm64:
  extends:
    - .rootfs-installer
    - .arch-arm64

installfs-arm64-staging:
  variables:
    MOBIAN_SUITE: "staging"
  extends:
    - .rootfs-installer
    - .arch-arm64

devicefs-pinephone-graphical:
  extends:
    - .devicefs
    - .device-pinephone
    - .environment-graphical
  needs:
    - rootfs-arm64-graphical

devicefs-pinephonepro-graphical:
  variables:
    MOBIAN_MINIRAMFS: "true"
  extends:
    - .devicefs
    - .device-pinephonepro
    - .environment-graphical
  needs:
    - rootfs-arm64-graphical-staging

#devicefs-pinetab-graphical:
#  extends:
#    - .devicefs
#    - .device-pinetab
#    - .environment-graphical
#  needs:
#    - rootfs-arm64-graphical

image-pinephone-graphical:
  extends:
    - .image
    - .device-pinephone
    - .environment-graphical
  needs:
    - rootfs-arm64-graphical

image-pinephonepro-graphical:
  extends:
    - .image
    - .device-pinephonepro
    - .environment-graphical
  needs:
    - rootfs-arm64-graphical-staging

#image-pinetab-graphical:
#  extends:
#    - .image
#    - .device-pinetab
#    - .environment-graphical
#  needs:
#    - rootfs-arm64-graphical

image-librem5-graphical:
  extends:
    - .image
    - .device-librem5
    - .environment-graphical
  needs:
    - rootfs-arm64-graphical

image-oneplus6-graphical:
  extends:
    - .image
    - .device-oneplus6
    - .environment-graphical
  needs:
    - rootfs-arm64-graphical-staging

image-pocof1-graphical:
  extends:
    - .image
    - .device-pocof1
    - .environment-graphical
  needs:
    - rootfs-arm64-graphical-staging

image-amd64-graphical:
  extends:
    - .image
    - .device-amd64
    - .environment-graphical
  needs:
    - rootfs-amd64-graphical

image-amd64-nonfree-graphical:
  extends:
    - .image
    - .device-amd64-nonfree
    - .environment-graphical
  needs:
    - rootfs-amd64-graphical

installer-pinephone-graphical:
  extends:
    - .installer
    - .device-pinephone
    - .environment-graphical
  needs:
    - installfs-arm64
    - devicefs-pinephone-graphical

installer-pinephonepro-graphical:
  extends:
    - .installer
    - .device-pinephonepro
    - .environment-graphical
  needs:
    - installfs-arm64-staging
    - devicefs-pinephonepro-graphical

#installer-pinetab-graphical:
#  extends:
#    - .installer
#    - .device-pinetab
#    - .environment-graphical
#  needs:
#    - installfs-arm64
#    - devicefs-pinetab-graphical
