include:
  - .gitlab-ci/job-definitions.yml
  - .gitlab-ci/global-declarations.yml
  - .gitlab-ci/devices.yml

rootfs-amd64-phosh:
  extends:
    - .rootfs-generic
    - .arch-amd64
    - .shell-phosh

rootfs-arm64-phosh:
  extends:
    - .rootfs-generic
    - .arch-arm64
    - .shell-phosh

installfs-arm64:
  extends:
    - .rootfs-installer
    - .arch-arm64

devicefs-pinephone-phosh:
  extends:
    - .devicefs
    - .device-pinephone
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

installer-pinephone-phosh:
  extends:
    - .installer
    - .device-pinephone
    - .shell-phosh
  needs:
    - installfs-arm64
    - devicefs-pinephone-phosh
